import { chromium } from '@playwright/test';
import { spawn } from 'node:child_process';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const server = spawn(process.execPath, ['tools/serve.mjs'], { env: { ...process.env, PORT: '4174' }, stdio: 'pipe' });
let browser;
try {
  await new Promise((resolve,reject) => { server.stdout.once('data',resolve); server.once('error',reject); server.once('exit',code=>reject(new Error(`Server exited ${code}`))); });
  browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1100}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message)); page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
  await page.goto('http://127.0.0.1:4174/study.html');
  await page.waitForFunction(()=>window.artStudy?.ready);
  await page.locator('#enter').click();
  assert.equal(await page.evaluate(()=>window.artStudy.snapshot().scene),'causeway');
  await page.locator('#scene-toggle').click();
  assert.equal(await page.evaluate(()=>window.artStudy.snapshot().scene),'courtyard');
  await page.locator('#scene-toggle').click();
  assert.equal(await page.evaluate(()=>window.artStudy.snapshot().scene),'causeway');
  await page.keyboard.down('KeyD'); await page.waitForFunction(()=>window.artStudy.snapshot().x>=480); await page.keyboard.up('KeyD');
  await page.keyboard.down('KeyD'); await page.keyboard.press('Space');
  await page.waitForFunction(()=>window.artStudy.snapshot().x>630 && window.artStudy.snapshot().grounded);
  await page.waitForFunction(()=>window.artStudy.snapshot().x>=1100); await page.keyboard.up('KeyD');
  await page.keyboard.press('KeyJ'); await page.waitForFunction(()=>window.artStudy.snapshot().hits===1);
  await page.waitForTimeout(400); assert.equal(await page.evaluate(()=>window.artStudy.snapshot().hits),1);
  await mkdir('tmp',{recursive:true}); await page.screenshot({path:'tmp/desktop-study.png',fullPage:true});
  await page.locator('#reset').click(); assert.equal(await page.evaluate(()=>window.artStudy.snapshot().x),240);
  await page.locator('#inspect').click(); assert.equal(await page.locator('#inspect').getAttribute('aria-pressed'),'true');
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  mobile.on('pageerror',e=>errors.push(e.message));
  await mobile.goto('http://127.0.0.1:4174/study.html');await mobile.waitForFunction(()=>window.artStudy?.ready);
  await mobile.locator('#enter').tap();
  const right=mobile.locator('[data-control="right"]');await right.dispatchEvent('pointerdown',{pointerId:1});
  await mobile.waitForFunction(()=>window.artStudy.snapshot().x>270);await right.dispatchEvent('pointerup',{pointerId:1});
  const stopped=await mobile.evaluate(()=>window.artStudy.snapshot().x);await mobile.waitForTimeout(150);
  assert.equal(await mobile.evaluate(()=>window.artStudy.snapshot().x),stopped);
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await mobile.screenshot({path:'tmp/mobile-study.png',fullPage:true});
  await mobile.locator('#scene-toggle').tap();
  assert.equal(await mobile.evaluate(()=>window.artStudy.snapshot().scene),'courtyard');
  await page.goto('http://127.0.0.1:4174/art/library/gallery.html');
  assert.equal(await page.locator('article').count(),15);
  await page.evaluate(async()=>{await Promise.all([...document.images].map(im=>{im.loading='eager';return im.decode();}));});
  assert.deepEqual(errors,[]);console.log('Desktop movement, gap jump, attack, reset, guides; mobile controls/layout: passed.');
} finally {await browser?.close();server.kill();}
