import{LEVEL,platforms}from"./cloister-sim.js";
import * as run from"./run.js";
import{pilgrimFrames,pilgrimScale,pilgrimPose}from"./pilgrim-poses.js";
import{crouchScale,crouchAnchors}from"./character-metrics.js";
const canvas=document.querySelector("#game"),ctx=canvas.getContext("2d"),$=q=>document.querySelector(q);
const W=run.enter("cloister");
let s=run.roomState(W),running=false,art={},atlas,last=0,acc=0,padPrevious={};const held=new Set,pulse={};
const keys={KeyA:"left",ArrowLeft:"left",KeyD:"right",ArrowRight:"right",Space:"jump",KeyW:"jump",ArrowUp:"jump",KeyS:"crouch",ArrowDown:"crouch",KeyJ:"attack",KeyX:"attack",KeyE:"interact"};
const load=path=>new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=()=>no(Error(path));i.src=path});
function keyed(im,magenta=false,checker=false){const c=document.createElement("canvas"),g=c.getContext("2d",{willReadFrequently:true});c.width=im.width;c.height=im.height;g.drawImage(im,0,0);const d=g.getImageData(0,0,c.width,c.height),a=d.data;if(magenta){for(let i=0;i<a.length;i+=4){const e=Math.min(a[i],a[i+2])-a[i+1];if(e>80)a[i+3]=0;else if(e>20)a[i+3]=255*(80-e)/60;}}else{const base=[a[0],a[1],a[2]],seen=new Uint8Array(c.width*c.height),queue=new Int32Array(seen.length);let head=0,tail=0;const add=n=>{if(n<0||n>=seen.length||seen[n])return;seen[n]=1;const i=n*4,dist=(a[i]-base[0])**2+(a[i+1]-base[1])**2+(a[i+2]-base[2])**2,neutral=Math.max(a[i],a[i+1],a[i+2])-Math.min(a[i],a[i+1],a[i+2]);if(checker?neutral<18&&a[i]>85:dist<=64)queue[tail++]=n};for(let x=0;x<c.width;x++){add(x);add((c.height-1)*c.width+x)}for(let y=0;y<c.height;y++){add(y*c.width);add(y*c.width+c.width-1)}while(head<tail){const n=queue[head++];a[n*4+3]=0;if(n%c.width)add(n-1);if(n%c.width<c.width-1)add(n+1);add(n-c.width);add(n+c.width)}}g.putImageData(d,0,0);return c}
function silhouette(sheet,outline){const c=document.createElement("canvas");c.width=sheet.width;c.height=sheet.height;const g=c.getContext("2d");g.beginPath();outline.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.clip();g.drawImage(sheet,0,0);return c}
function start(){running=true;$("#start-overlay").classList.add("hidden");canvas.focus()}function reset(){s=run.restart(W,"cloister");held.clear();start()}$("#enter").onclick=start;$("#reset").onclick=reset;
addEventListener("keydown",e=>{if(document.activeElement!==canvas)return;const a=keys[e.code];if(a){e.preventDefault();held.add(a);if(!e.repeat&&!['left','right','crouch'].includes(a))pulse[a]=true}});addEventListener("keyup",e=>held.delete(keys[e.code]));addEventListener("blur",()=>held.clear());
for(const b of document.querySelectorAll("[data-control]")){b.onpointerdown=e=>{e.preventDefault();start();const a=b.dataset.control;held.add(a);if(!['left','right','crouch'].includes(a))pulse[a]=true;b.setPointerCapture(e.pointerId)};for(const n of["pointerup","pointercancel","lostpointercapture"])b.addEventListener(n,()=>held.delete(b.dataset.control))}
function input(){const i={left:held.has("left"),right:held.has("right"),crouch:held.has("crouch"),jump:!!pulse.jump,attack:!!pulse.attack,interact:!!pulse.interact},pad=[...(navigator.getGamepads?.()||[])].find(Boolean);if(pad){i.crouch||=pad.axes[1]>.5||pad.buttons[13]?.pressed;i.left||=pad.axes[0]<-.25||pad.buttons[14]?.pressed;i.right||=pad.axes[0]>.25||pad.buttons[15]?.pressed;for(const[a,n]of Object.entries({jump:0,attack:2,interact:1})){const down=!!pad.buttons[n]?.pressed;if(down&&!padPrevious[a])i[a]=true;padPrevious[a]=down}}return i}
function platform(p){
  ctx.fillStyle="#26323a";ctx.fillRect(p.x,p.y,p.w,p.h??150);
  ctx.save();ctx.beginPath();ctx.rect(p.x,p.y,p.w,60);ctx.clip();
  for(let x=p.x;x<p.x+p.w;x+=240)ctx.drawImage(art.capCenter,x,p.y-7.5,240,60);
  ctx.restore();ctx.strokeStyle="#9baaa4";ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+p.w,p.y);ctx.stroke();
}
function hero(){let f=atlas.frames[0],sheet=art.hero,scale=144/418;if(s.attack>0)f=atlas.frames[s.attack>.28?5:s.attack>.1?6:7];else if(!s.grounded){const frames=[{x:40,y:20,width:415,height:680,pivotX:240,pivotY:644},{x:475,y:130,width:420,height:390,pivotX:245,pivotY:354},{x:910,y:130,width:400,height:580,pivotX:235,pivotY:542}];f=frames[s.vy<-140?0:s.vy>140?2:1];sheet=art.air;scale=144/510}else if(Math.abs(s.vx)>0)f=atlas.frames[1+(Math.floor(s.walk/.115)%4)];ctx.save();ctx.translate(s.x,s.y);ctx.scale(s.facing,1);if(s.invulnerable>0&&Math.floor(s.time*15)%2)ctx.globalAlpha=.4;if(s.crouching){const n=s.attack>0?(s.attack>.28?3:s.attack>.12?4:5):Math.abs(s.vx)>0?1+(Math.floor(s.walk/.18)%2):0,[x,y]=crouchAnchors[n];ctx.drawImage(art.crouchFrames[n],-x*crouchScale,-y*crouchScale,1536*crouchScale,1024*crouchScale)}else ctx.drawImage(sheet,f.x,f.y,f.width,f.height,-f.pivotX*scale,-f.pivotY*scale,f.width*scale,f.height*scale);ctx.restore()}
function enemy(){const e=s.enemy;if(e.hp<=0)return;const pose=pilgrimPose(e),f=pilgrimFrames[pose];ctx.save();ctx.translate(e.x,e.y);ctx.scale(e.facing*f.facing,1);if(e.mode==='hurt')ctx.globalAlpha=.5;ctx.drawImage(art.enemyFrames[pose],-f.pivot[0]*pilgrimScale,-f.pivot[1]*pilgrimScale,1376*pilgrimScale,768*pilgrimScale);ctx.restore();if(e.mode==='windup'){ctx.fillStyle="#ffcc77";ctx.font="28px Georgia";ctx.fillText("!",e.x-5,e.y-170)}ctx.fillStyle="#392832";ctx.fillRect(e.x-22,e.y-150,44,4);ctx.fillStyle="#d0a079";ctx.fillRect(e.x-22,e.y-150,44*e.hp/3,4)}
function draw(){ctx.fillStyle="#0b131b";ctx.fillRect(0,0,1280,720);const fog=ctx.createLinearGradient(0,0,0,720);fog.addColorStop(0,"#18242d");fog.addColorStop(1,"#081017");ctx.fillStyle=fog;ctx.fillRect(0,0,1280,720);ctx.save();ctx.translate(-s.camera*.18,0);ctx.globalAlpha=.42;for(let x=-40;x<5200;x+=320)ctx.drawImage(art.arch,119,41,786,945,x,90,430,520);ctx.restore();ctx.save();ctx.translate(-s.camera,0);for(const p of platforms)platform(p);ctx.drawImage(art.lever,s.leverOn?1024:0,0,1024,1024,LEVEL.lever-45,500,90,90);ctx.drawImage(art.grate,LEVEL.gate-65,s.leverOn?275:438,130,162);if(!s.vialTaken)ctx.drawImage(art.vial,1868,520+Math.sin(s.time*3)*5,64,64);enemy();hero();ctx.fillStyle="#d9bc82";ctx.font="17px Georgia";for(const[x,t]of[[180,"I · BROKEN ARCADE"],[1280,"II · VIAL LEDGE"],[2140,"III · LEVER COURT"],[3220,"IV · GATE WALK"]])ctx.fillText(t,x,220);ctx.fillText("E · PULL",LEVEL.lever-35,475);ctx.restore();$("#health").textContent="♥".repeat(s.hp)+"♡".repeat(5-s.hp);$("#progress").value=s.x/LEVEL.width*100;$("#notice").textContent=s.noticeTime?s.notice:"";$("#status").textContent=s.complete?"STAGE BLOCKOUT COMPLETE":s.x<1100?"BROKEN ARCADE":s.x<2100?"VIAL LEDGE":s.x<3000?"LEVER COURT":"GATE WALK"}
function tick(now){if(running){acc+=Math.min((now-last)/1000,.1);while(acc>=1/60){if(run.step(W,input(),1/60,{}))return;for(const k of Object.keys(pulse))delete pulse[k];acc-=1/60}}last=now;draw();requestAnimationFrame(tick)}
try{const paths=["art/contributions/08-ruined-cloister/v001/exports/cloister-arch-span-v001.png","art/contributions/world-02-ruined-cloister/v002/exports/platform-cap-center-v002.png","art/contributions/15-mechanisms/v001/exports/lever-v001.png","art/contributions/15-mechanisms/v003/exports/grate-v001.png","art/contributions/14-pickups-and-relics/v001/exports/healing-vial-v001.png","art/production/bellwarden/bellwarden-pilot-v001.png","art/production/bellwarden/bellwarden-airborne-v001.png","art/production/enemies/hollow-pilgrim-motion-v001.png","art/contributions/01-bellwarden-crouch/v001/source/crouch-generated-v001.png"];[art.arch,art.capCenter,art.lever,art.grate,art.vial,art.hero,art.air,art.enemy,art.crouch]=await Promise.all(paths.map(load));atlas=await fetch("art/production/bellwarden/bellwarden-pilot-v001.json").then(r=>r.json());art.hero=keyed(art.hero,true);art.air=keyed(art.air);art.enemy=keyed(art.enemy);art.enemyFrames=Object.fromEntries(Object.entries(pilgrimFrames).map(([n,f])=>[n,silhouette(art.enemy,f.outline)]));const crouch=keyed(art.crouch,false,true);for(const blade of[[[266,362],[480,417],[268,376]],[[814,337],[1019,383],[814,350]],[[1370,342],[1518,409],[1367,356]],[[163,768],[404,818],[160,781]],[[972,725],[1188,732],[972,741]],[[1374,796],[1508,763],[1380,809]]])crouch.getContext("2d").drawImage(silhouette(art.crouch,blade),0,0);const outlines=[[[0,110],[505,110],[505,480],[0,480]],[[525,110],[1020,110],[1020,480],[525,480]],[[1045,110],[1536,110],[1536,480],[1045,480]],[[0,610],[510,610],[510,980],[0,980]],[[515,610],[1200,610],[1200,750],[980,750],[980,980],[515,980]],[[1070,840],[1200,700],[1200,610],[1536,610],[1536,980],[1070,980]]];art.crouchFrames=outlines.map(o=>silhouette(crouch,o));window.cloister={ready:true,snapshot:()=>structuredClone(s)};requestAnimationFrame(tick)}catch(e){$("#notice").textContent="Stage art failed to load: "+e.message;console.error(e)}
